### ISSUE TITLE
check default value for cluster_label_prop's mode

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1017]
see https://github.com/igraph/rigraph/pull/1005#issuecomment-1862642830 by @szhorvat

**Comment by szhorvat** [comment]
Let's spell out the issue here:

The default behaviour of `cluster_label_prop` is to treat directed graphs as such. It is unclear how much sense directed label propagation makes. Should the default be to ignore edge directions, [as the C docs recommend](https://igraph.org/c/html/latest/igraph-Community.html#igraph_community_label_propagation)?

@vtraag Do you think that any change should be made in how each community detection function handles directed graphs by default?

Here's a summary of the current situation:

Currently, edge directions are supported by `cluster_edge_betweenness`, `cluster_infomap` and `cluster_label_prop`. All of these treat directed edges as such by default. It is debatable whether considering edge directions makes sense for `cluster_edge_betweenness` and `cluster_label_prop`.  `cluster_infomap`  has no option for ignoring edge directions, and it wasn't documented that it supports directed graphs (I just fixed this).

Of the rest, there is _some_ chance that directed graph support might be added to `cluser_leiden` / `cluster_louvain` / `cluster_optimal` in the future. Currently they don't.

----

Since it's not entirely clear to me what the best choice is for each function, I'd suggest to leave things as they are.

**Comment by vtraag** [comment]
> @vtraag Do you think that any change should be made in how each community detection function handles directed graphs by default?

I have no strong opinion on a default for this. If the direction is supported by the algorithm, it might make sense to keep it as the default (although in some cases, it might be a bad choice because it doesn't make much sense, e.g. label propagation). 

> Since it's not entirely clear to me what the best choice is for each function, I'd suggest to leave things as they are.

So,this sounds reasonable to me.
