### ISSUE TITLE
include directories listed in CFLAGS and CXXFLAGS instead of PKG_CPPFLAGS

### ISSUE THREAD

**Issue by pooryorick** [igraph/rigraph#111]
In R, only PKG_CPPFLAGS overrides the include directories that R records in its configuration when it is built, so header conflicts can occur if -I arguments are used in PKG_CFLAGS and PKG_CXXFLAGS, as rigraph does.  In our environment, the following change allowed the build to succeed:

``` diff
--- igraph/src/Makevars.in      2015-06-25 21:04:46.000000000 -0400
+++ igraph.new/src/Makevars.in  2015-08-21 17:56:50.000483000 -0400
@@ -1,12 +1,12 @@

-PKG_CFLAGS=-DUSING_R -I. -Iinclude -Ics -Iglpk -Iplfit \
-        -ICHOLMOD/Include -IAMD/Include -ICOLAMD/Include \
+PKG_CPPFLAGS=-DNDEBUG -DUSING_R -DUSING_R -DIGRAPH_THREAD_LOCAL=/**/ \
+       -DNDEBUG -Iprpack -I. -Iinclude -DPRPACK_IGRAPH_SUPPORT -Iprpack \
+       -I. -Iinclude -Ics -Iglpk -Iplfit -ICHOLMOD/Include -IAMD/Include \
+       -ICOLAMD/Include \
        -ISuiteSparse_config \
        @CPPFLAGS@ @CFLAGS@ -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT\
        -DPACKAGE_VERSION=\"@PACKAGE_VERSION@\" -DINTERNAL_ARPACK \
        -DIGRAPH_THREAD_LOCAL=/**/
-PKG_CXXFLAGS= -DUSING_R -DIGRAPH_THREAD_LOCAL=/**/ -DNDEBUG -Iprpack -I. \
-       -Iinclude -DPRPACK_IGRAPH_SUPPORT
 PKG_LIBS=@XML2_LIBS@ @GMP_LIBS@ @GLPK_LIBS@ $(FLIBS) $(LAPACK_LIBS) $(BLAS_LIBS)

 all: $(SHLIB)
```

**Comment by gaborcsardi** [comment]
Thanks! Could you please send a PR?

Btw. the current version builds on several platforms, where did you have problems with it?

**Comment by rundel** [comment]
This is partially related to issue #135, the package fails to build because `PKG_CFLAGS` and `PKG_CXXFLAGS` do not overwrite the defaults set by R which causes the compiler to prefer looking in `/usr/local/include` which may have alternative versions of CHOLMOD headers available (in this case because I had suite-sparse installed). 

Switching to `PKG_CPPFLAGS` does not entire solve #135 since Homebrew screws up Makeconf by appending `-I/usr/local/include` to *all* of the `CPPFLAGS` variables including `R_XTRA_CPPFLAGS` which gets included in the compiler call before `PKG_CPPFLAGS`. I've gotten in touch with them about fixing that specific issue, which along with this should solve #135.

**Comment by ntamas** [comment]
I think this is now fixed in the latest version, which adds the include path directives to `PKG_CPPFLAGS` where it should have been in the first place. `PKG_CFLAGS` and `PKG_CXXFLAGS` is now used only for visibility flags (i.e. `$(C_VISIBILITY)` and `$(CXX_VISIBILITY)`).
