### ISSUE TITLE
Documentation for power_centrality

### ISSUE THREAD

**Issue by reuning** [igraph/rigraph#1277]
This is a minor change, and I'd be happy to do a pull request but I wasn't sure if there was a reason. 

For `power_centrality()` it would be helpful to have a line in the documentation that indicates that by default it estimates out-centrality (not sure about the language there) and that in-centrality can be estimated by using `t()`. 

I say this as I'm teaching using Borgatti et al's Analyzing Social Networks Using R book, but am having my students just use igraph instead. It took me a bit of tinkering to figure this out, especially since `eigen_centrality()` defaults to in-centrality measure.

**Comment by maelle** [comment]
@reuning thanks so much, and great to hear you're using igraph for teaching.

@szhorvat could you provide please some feedback on the phrasing, is "out-centrality" correct?

**Comment by szhorvat** [comment]
I don't have the time right now to look into this, as I'd need a reminder on the concept of power centrality, which I have not used so far. Note that this is implemented in pure R.

I note this line in the documentation:

> power_centrality() will not symmetrize your data before extracting eigenvectors; don't send this routine asymmetric matrices unless you really mean to do so.

This suggests that directed graphs are not intended to work.

I'll take a look when I'm back.

@reuning, I believe I know what you mean by "out-centrality", but it's probably better to use an explicit formula for the definition, as that is unambiguous. If you have time to work on this, it would be useful to do the following:

 - Check if the original paper is dealing with undirected or directed graphs (I guess you already know this since you're teaching it).
 - If we need directed graphs, check if the implementation is correct, and what trouble non-symmetric matrices may cause
 - Submit a PR for the docs which uses a clearer description. I like the description [here](http://www.analytictech.com/ucinet/help/2ahtpd8.htm), with the recursive form and the phrasing "The centrality of each vertex is therefore determined by the centrality of the vertices it is connected to."

**Comment by reuning** [comment]
I know that it _can_ be used on directed networks, but am not that familiar with it. I'd be happy to dive in to it though and see if I can get some more solid answers to these questions.

**Comment by reuning** [comment]
So coming back to this, Bonacich (1987) explicitly discusses non-symmetric matrices and provides an example and interpretation. The current implementation should work for directed graphs, at least I don't see anything wrong with it. I'll write up some documentation later this week and submit a PR.
