### ISSUE TITLE
TODOs in `socnet.R`

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1460]
There are a few TODOs in `socnet.R` but it made me wonder why igraph has this interactive interface. Should it still be supported?

**Comment by szhorvat** [comment]
IMO interactive plotting and graph editing (`tkplot()`) is very useful. We invested in creating such an interface in Mathematica, and many users appreciate it. Perhaps the R version just needs more advertisement.

As for the analysis UI (`tkigraph()`), I am much more skeptical about this. It might make more sense to allow other GUI tools to integrate well with igraph rather than maintain this ourselves.

Both of these are my personal opinion, and I expect others may disagree.

**Comment by krlmlr** [comment]
I don't see evidence of this being used. Can we move this part to a separate package on GitHub?

https://github.com/search?q=tkigraph+language%3Ar+-path%3A**%2Fsocnet.R++-path%3A**%2Ftkigraph.Rd++-path%3A**%2Ftkigraph.html&type=code

**Comment by krlmlr** [comment]
`tkplot()` seems to be used.

**Comment by krlmlr** [comment]
Is there a more modern HTML- or JS-based alternative for `tkplot()` ?

**Comment by maelle** [comment]
If we remove `tkigraph()` in a release and someone complains, at least we'd know it's used? :sweat_smile: (I obviously don't want to willingly break anyone's teaching materials)

**Comment by szhorvat** [comment]
Factoring out `tkigraph` to a separate package (which received minimal maintenance for a little while) sounds like the best idea. This way:

 - We do hear complaints if someone uses it.
 - We do have an immediate solution for people who complain.
 - Support can be dropped completely if there are no complaints.

We did the same with the spectral coarse graining functions in the C core, https://github.com/igraph/igraph-scg  Keeping them functional after igraph updates turned out to take near-zero work.
