### ISSUE TITLE
R: Implement GephiGraphStreamer

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/rigraph#15]
_From @supersambo on January 28, 2014 12:44_

as it's done for the python version http://igraph.sourceforge.net/doc/python/igraph.remote.gephi.GephiGraphStreamer-class.html
- [ ] Sending graphs to Gephi.
- [ ] Receiving graphs from Gephi.
- [ ] Manipulating graphs in Gephi.
- [ ] Connecting an R graph to a Gephi graph.

This last one is not straightforward, because R objects are immutable. But we can have an environment (or reference class) that contains an igraph graph.

_Copied from original issue: igraph/igraph#572_

**Comment by gaborcsardi** [comment]
Even getting the graph from Gephi is tricky, because gephi does not close the connection, so we can never be use when we got the whole graph. I am not sure what to do about this.

**Comment by gaborcsardi** [comment]
Gephi is also slightly broken, when adding a new node, you get this:
```
{"cn":{"80":{}}}
{"an":{"80":{"g":0.6,"b":0.6,"r":0.6,"Degree":0,"Label":"xxx","z":0,"y":414.5425,"x":29.648602,"size":10}}}
{"cn":{"80":{"Label":"xxx"}}}
```

I.e. first there is a 'change node' operation on a non-existing node. 

Also, when grouping vertices in gephi, the streamer adds a new node, kind of strange.

**Comment by ntamas** [comment]
Gephi has not been updated since 2017 or so, and although it seems like there's a revival attempt now (judging from the Gephi blog), it's unclear whether the streaming API will remain or not. The Python interface is about to remove support for the graph streamer as well until the situation becomes clearer and Gephi gains momentum again, so closing this for the time being to clean up the issue tracker.

Feel free to reopen if it's still relevant.
