### ISSUE TITLE
Weighted betweenness can give non-integer values

### ISSUE THREAD

**Issue by adndebanane** [igraph/rigraph#314]
Dear igraph authors and contributors,

I am trying to compute the weighted betweenness centrality on undirected graphs. The function `betweenness()` from igraph returns non-integer values even with `normalized = FALSE`. Could this be related to [this issue](https://github.com/igraph/igraph/issues/950)?

Reproducible example:

```r
from <- c(1, 2, 3, 3, 3, 4, 6, 7, 2, 9, 5, 7, 9, 9, 5, 8)
to <- c(4, 3, 6, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
edges <- cbind(from, to)
edges.dists <- c(1.9617537, 0.9060834, 2.2165446, 1.6251956,  
	               2.4473929, 0.5913490, 8.7093236, 2.8387330,
	               6.1225042, 20.7217776, 6.8027218, 16.3147479,
	               5.2605598, 6.6816853, 4.9482123, 1.8989790)

g <- graph.data.frame(edges, directed = FALSE)
betweenness(g, weights = edges.dists)
```
returns the following BCs, with fourth node being non-integer
```
    1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16 
 0.00 44.00 71.00 47.25 27.00 44.00 38.00 14.00 39.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00 
```
Edit: networkX called with `betweenness_centrality(G, normalized=False, weight='weight')` returns a different (and integer) value for the fourth node:
```
{1: 0.0, 2: 44.0, 3: 71.0, 4: 46.0, 5: 27.0, 6: 44.0, 7: 38.0, 8: 14.0, 9: 39.0, 10: 0.0, 11: 0.0, 12: 0.0, 13: 0.0, 14: 0.0, 15: 0.0, 16: 0.0}
```

Session info
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin18.0.0 (64-bit)
Running under: macOS  10.14.2

other attached packages:
[1] igraph_1.2.2
```

**Comment by szhorvat** [comment]
The development version, which received some fixes, returns this result:

```
   1    2    3    4    6    7    9    5    8   10   11   12   13   14   15   16 
 0.0 44.0 71.0 36.5 44.0 38.0 39.0 27.0 14.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 
```

You will notice that some of these are not integers either. However, there are actually multiple paths with the same lengths between some vertices. The paths `3-6` and `3-4-6` have the same lengths.

The weights are as follows:

`3-6`: `2.2165446`
`3-4`: `1.6251956`
`4-6`:  `0.5913490`

I wonder how you chose the weights for this graph, given that the latter two numbers add up to the first.

Why might networkx return something different then? Comparing floating point numbers is hard: small differences are easily introduces due to numerical roundoff errors. Try this in R, and you get `FALSE`: `1/7 + 1/7 + 1/7 + 1/7 + 1/7 + 1/7 + 1/7 == 1`. igraph's betweenness code performs comparisons with tolerances to mitigate this problem, and is able to detect paths of equal lengths even in weighted graphs. 

I verified the result I get in the development version using a custom, tolerance-aware implementation in Mathematica.

Since now the result is correct, I am closing this issue.

**Comment by szhorvat** [comment]
P.S. If you have the R development tools installed, you can get the dev version of R/igraph 1.3 using `remotes::install_github("igraph/rigraph@master")`

**Comment by szhorvat** [comment]
@ntamas This would make a good test case, do you want to add it to the test suite?

**Comment by ntamas** [comment]
Do you mean the R test suite or the C core?

**Comment by szhorvat** [comment]
I mean R, as it should be easy (all code available in top post).
