### ISSUE TITLE
read_graph uses too much memory when node names use large numbers

### ISSUE THREAD

**Issue by fmccown** [igraph/rigraph#337]
When I use read_graph() from igraph to read a short text file of nodes that use large numbers, read_graph() will cause RStudio to consume several gigabytes of RAM (verified by watching the Task Manager) and eventually freeze my computer when 95%+ memory is used. I've replicated this problem on multiple Win10 machines with a fresh install of R, RStudio, and igraph.

edges file:

279360686 24702689
18030304 18553324
38719238 309129656
41298106 250831586
164052930 16064415
404647567 38719238

Code:

g <- read_graph("edges", directed=F)

If I replace the node names with small numbers or alpha chars, no problems occur. These numbers are coming from a popular online network data set.

**Comment by ntamas** [comment]
The edge list format in igraph assumes that the nodes are indexed with consecutive integers from zero. This means that igraph will create millions of isolated nodes for your input. Use `read_graph("edges", format="ncol", directed=F)`; this will assume that the file contains symbolic vertex "names" instead of vertex indices.
