### ISSUE TITLE
Modularity is implemented for undirected graphs only.

### ISSUE THREAD

**Issue by pipii355** [igraph/rigraph#351]
I wanna use the method of community  detection based on edge betweenness.

Usage in R:
cluster_edge_betweenness(graph, weights = E(graph)$weight,
  directed = TRUE, edge.betweenness = TRUE, merges = TRUE,
  bridges = TRUE, modularity = TRUE, membership = TRUE)

my code:
   gg<-graph.adjacency(data,mode="directed",weighted=T)
    a<-cluster_edge_betweenness(gg,weights = E(gg)$weight, directed = TRUE, edge.betweenness = 
          TRUE, merges = TRUE,  bridges = TRUE, modularity = TRUE, membership = TRUE)
but the warning messages:
1.Modularity is implemented for undirected graphs only.
2.Membership vector will be selected based on the lowest modularity score.

**Comment by LTribelhorn** [comment]
I don't really understand the issue of @pipii355 but based on the title I suppose this is a feature request for the implentation of directed modularity. If this is indeed the case, I would like to ask if there are any plans for implementing this soon or if someone has found a workaround or has already written a function.

The mathematical equation for this calculation can be found in [Leicht & Newman (2008)](http://dx.doi.org/10.1103/PhysRevLett.100.118703) and the implementation should be very simple because it should differ only slightly from the already implemented modularity function.

**Comment by szhorvat** [comment]
This was recently implemented in igraph's C core, it just needs to make its way into the R interface.

**Comment by LTribelhorn** [comment]
Thanks for the quick reply.
Is there any way to speed this up or to already use the C-function?

**Comment by szhorvat** [comment]
This works in the current development version (to become 1.3.0), which can be installed using the instructions here: https://github.com/igraph/rigraph/#installation (you need the R development tools to install it, as it will be compiled from source).
