### ISSUE TITLE
graph_from_incidence_matrix Error: cannot add edges, Invalid vertex id

### ISSUE THREAD

**Issue by ImNotaGit** [igraph/rigraph#353]
I would like to create a directed bipartite graph from an incidence matrix. I need to have cases where there are two edges connecting two nodes in both direction, with each of these edges having a different numerical weight. However, it seems that igraph does not allow this. I would like to know whether this is a bug, or simply not implemented, and whether there is a way to work around this. Thanks!

Here is a simple example:
```
mat <- matrix(c(1,2,0,1,0,1), 3)
rownames(mat) <- c("a","b","c")
colnames(mat) <- c("X","Y")
```
This is what mat looks like:
```
##   X Y
## a 1 1
## b 2 0
## c 0 1
```
then
```
graph_from_incidence_matrix(mat, directed=TRUE, mode="all", weighted=TRUE, multiple=FALSE)
```
gives the error:
```
## Error in add_edges(res, edges, attr = weight) : 
##   At type_indexededgelist.c:272 : cannot add edges, Invalid vertex id
```

**Comment by ntamas** [comment]
The underlying bug is now fixed, but there is still an open question: how shall the weights be handled in this case? Since we are creating edges in both directions between a pair of vertices, shall the weights of these edges be _equal_ to the one specified in the incidence matrix, or shall it be _half_ the weight in the matrix s.t. the sum of the weights of the created edge pair matches the one in the matrix? (Right now it's the former).
