### ISSUE TITLE
One graph dimension (x or y) constant or defined

### ISSUE THREAD

**Issue by Close-your-eyes** [igraph/rigraph#444]
Dear all,

is it possible to define one dimension (x or y) for vertices while the other is optimized by any of the layout-algorithms to minimizes the number of crossing edges?

I want to make a pedigree layout (or family tree) where the y-dimension has an implication (~generation).

Phrased differently: is there any layout algorithm which allows to define which vertices should be place on equal x or y values?

**Comment by szhorvat** [comment]
You can try to use the Sugiyama layout, which is designed for directed acyclic graphs and for trees. It allows for specifying the layers (i.e. "y coordinate") of vertices.

For future support requests (as opposed to bug reports), please use [the forum](https://igraph.discourse.group/) instead of the bug tracker.
