### ISSUE TITLE
max_cardinality wrong result in graphs with differing vertex names and indices

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#450]
`max_cardinality` returns wrong results on graphs with differing vertex names and indices.

Currently, it interprets the `alpha` values returned by the C function as vertex indices and converts them to vertex names. However, these are not vertex indices: they are simply ranks.

See here for more info:

https://igraph.discourse.group/t/question-about-function-max-cardinality/639

Proposed solutions:

 - Return `alpha` values as they are
 - Optionally: return the vertex list in maximum cardinality order as a different, 3rd component of the result

**Comment by ntamas** [comment]
I think that the code for the `max_cardinality` function in R is generated by `stimulus.py` and the reason why it converts the output is because it is declared like this in `interfaces/functions.def` in the C core:

> GRAPH graph, OUT VERTEXSET alpha, OUT VECTORM1_OR_0 alpham1

which basically means that the `alpha` vector returned by the C function is a list of vertex IDs.

I think the intention was to treat `alpha` as a rank vector and `alpham1` as its inverse, which could indeed be treated as a list of vertex IDs. So, the correct typing should be:

> GRAPH graph, OUT VECTORM1 alpha, OUT VERTEXSET_OR_0 alpham1

because `alpha` is not optional (hence no `_OR_0` suffix) and it contains the rank to be shown in R _minus 1_ (hence the `M1` suffix -- note that R is 1-based while C is 0-based, so the ranks returned from C will be 0-based). `alpham1` is then `VERTEXSET_OR_0` because the C core accepts a null vector there.

I can change this now in the C core but I'd rather not do this without @vtraag giving some feedback about whether it solves the problem in R.

**Comment by szhorvat** [comment]
This should be fixed before 1.3.0.

**Comment by szhorvat** [comment]
This appears to be corrected in `develop` (C/igraph):

https://github.com/igraph/igraph/blob/develop/interfaces/functions.yaml#L738

But I think `alpha ON graph` can be removed from `DEPS`, @ntamas, right?

----

However, this is still unfixed on `master`:

https://github.com/igraph/igraph/blob/master/interfaces/functions.yaml#L692

----

It needs to be corrected in `functions.yaml` and the docs need an update (using the C docs as guidance).

**Comment by ntamas** [comment]
Yes, the `alpha ON graph` part can be removed from `DEPS`. I'll fix this in both `master` and `develop` in C-igraph.

**Comment by ntamas** [comment]
This is now sorted out both in the C core and in the R interface.
