### ISSUE TITLE
At vector.pmt:444 : cannot reserve space for vector, Out of memory

### ISSUE THREAD

**Issue by mostafiz67** [igraph/rigraph#456]
I have a large graph (`vertex# 9,634 and edges# 454,691`). I am using `shortest.paths()` function to get the shortest path matrix.

But, unfortunately, I am getting an error, **At vector.pmt:444 : cannot reserve space for vector, Out of memory.**

I am using `R version 3.6.3 (2020-02-29) Platform: x86_64-pc-linux-gnu (64-bit) Memory: 64 GB`

Sample code is given below:

```
test <- read.csv("~/data.csv")
g1 <- test[1:5,]
graph1 <- graph_from_data_frame(g1, directed = FALSE)
E(graph1)$weight <- is.numeric(g1$weight)

mat_1 <- shortest.paths(graph1) # getting error in this line
```

I have gone through several posts and found one piece of information [here](https://lists.nongnu.org/archive/html/igraph-help/2010-06/msg00018.html) but this code is not fulfilling my purpose. I need the whole matrix and then I have to do some filter in this matrix. For example, after getting the whole matrix, I will take only the cell values which have 2. Regarding filtering, I have another post [here](https://stackoverflow.com/questions/66507728/how-to-take-only-one-connection-from-a-matrix).

Badly need your help and suggestion.

For your kind information:` I am also trying to use 87GB in a cluster but getting the same error!`

**Comment by vtraag** [comment]
> I have gone through several posts and found one piece of information [here](https://lists.nongnu.org/archive/html/igraph-help/2010-06/msg00018.html) but this code is not fulfilling my purpose. I need the whole matrix and then I have to do some filter in this matrix.

Why does this post not help? In principle you can calculate the shortest paths from each vertex, and store only the entries that satisfy your filtering criterium. 

Another possibility, if you just need to find all nodes that are at distance 2 from each other node you can also use the [`ego`](https://igraph.org/r/doc/ego.html) function. This function gets you all nodes within a specific distance, but you can first retrieve nodes at distance 2 and then remove the nodes that are at distance 1.

Regardless, it is a bit strange to see this error with 64GB of memory. In principle, it needs to allocate only about 0.7Gb. Could you perhaps share the dataset that triggers this issue so that we can reproduce it?

**Comment by mostafiz67** [comment]
Thank you for your reply. I apologize, I have an error with my dataset. Actually, my dataset contains 4 columns instead of 3 columns and that's why I was getting errors. 

However, I will check the `ego` function and will let you know. 

> Why does this post not help? In principle you can calculate the shortest paths from each vertex, and store only the entries that satisfy your filtering criterium.

When I was using the concept given in this post, I was getting only the last vertex result. Somehow, the result of the `sp` variable was replacing one with the next one. Like, If I have 3 vertexes then I was getting the result only the 3rd one.
