### ISSUE TITLE
Issue loading graph 

### ISSUE THREAD

**Issue by samlipworth** [igraph/rigraph#472]
Trying to load a graph into igraph - works with R version 3.4.0 and used to work with R version 4.0 but since "upgrading" to R version 4.1 and R studio to v1.5.244 it now craches giving the error:

```
g<-read.graph('test.gml',format='gml')

read out of range
missing nul-terminator 
ERROR elf_dynamic_array_reader.h:61] tag not found
opendir: No such file or directory

```

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] igraph_1.2.6

loaded via a namespace (and not attached):
[1] compiler_4.1.0  magrittr_2.0.1  tools_4.1.0     pkgconfig_2.0.3
```

**Comment by gaborcsardi** [comment]
According to your session info, igraph is already loaded and attached. If
this error happens in `read.graph`, then you'll need to show us the file
that you are reading.

**Comment by samlipworth** [comment]
Thanks for getting back to me. Please see the graph attached.
________________________________

**Comment by ntamas** [comment]
I'm afraid that Github strips all attachments from issue replies submitted via email. Please upload the graph directly to the issue tracker or upload it to Pastebin (or some other similar service) and share the link with us.

**Comment by samlipworth** [comment]
oops sorry - hopefully this works
[tiny_graph.gml.gz](https://github.com/igraph/rigraph/files/6899603/tiny_graph.gml.gz)

**Comment by ntamas** [comment]
Thanks, I've tried it on my machine with R 4.1.0 (from the command line) and it works just fine; also, the GML file seems okay so I'm not sure what's going on here, but it's probably platform-dependent. I'm on macOS, but I'm going to try this shortly on a remote Ubuntu machine.

**Comment by ntamas** [comment]
[This RStudio issue](https://github.com/rstudio/rstudio/issues/7310) seems very similar and it ended up being a graphic driver issue. Can you try loading the same graph from R itself, without using RStudio's GUI? If it works without the GUI, then I'm pretty sure it's an RStudio issue.

**Comment by ntamas** [comment]
I managed to get a crash on Ubuntu 20.04 with R 4.1.0, using the command line, so it's not RStudio's fault. I'll investigate.

**Comment by ntamas** [comment]
Okay, so I've found the problem. On one hand, the input file does not seem to be a valid GML file; on the other hand, this shouldn't crash igraph of course (and we'll try to fix it in the next release).

The problem with the input file is that there are several node and edge attributes that appear multiple times for the same node. For instance, this is the first node of the graph:

```
node [
    id 0
    label "339"
    size 2
    centroid "0_0_11"
    maxLenId 0
    members 0
    members 3
    seqIDs "0_0_11"
    seqIDs "3_0_12"
    hasEnd 0
    protein "LIPLPSGTKIWLVAGITDMRNGFNGLAAKVQTTLKDDPMSGHVFIFRGRNGSQVKLLWSTGDGLCLLTKRLERGRFAWPSARDGKVFLTPAQLAMLLEGIDWRQPKRLLTSLTML"
    dna "TTGATCCCATTACCATCAGGGACAAAGATCTGGCTGGTCGCTGGCATCACCGATATGAGAAACGGCTTCAACGGCCTGGCGGCAAAGGTGCAGACGACGCTGAAAGACGATCCGATGTCAGGTCACGTTTTTATCTTCCGTGGGCGTAATGGCAGTCAGGTAAAGCTCCTCTGGTCTACCGGCGATGGACTGTGTCTGCTGACCAAACGGCTGGAGCGCGGCCGCTTCGCCTGGCCGTCAGCCCGGGATGGCAAAGTGTTCCTCACACCGGCACAGCTGGCGATGCTCCTTGAAGGTATCGACTGGCGGCAGCCTAAAAGACTGCTTACGTCACTGACTATGTTGTAG"
    annotation "tnpB_1"
    description "IS66 family insertion sequence element accessory protein TnpB"
    lengths 348
    lengths 348
    longCentroidID 348
    longCentroidID "0_0_11"
    paralog 0
    mergedDNA 0
    genomeIDs "0;3"
    geneIDs "0_0_11;3_0_12"
    degrees 2
    name "tnpB_1"
  ]
```

`lengths`, `members`, `seqIDs` and `longCentroidID` appear multiple times in the attribute list; this is not supported by igraph and I'm pretty sure this was never supported in the official GML specification either (although all the links that I've had for the GML specification are now broken so I cannot confirm it). Attributes appearing multiple times would not be a problem if they were of the same type; however, for `longCentroidID`, the first attribute value is a number and the second is a string. When igraph reads the input file, it establishes the attribute as being numeric when it sees the first occurrence, and then crashes when it sees the second occurrence with a string type.

Furthermore, there are several attributes that seem to have a _valid_ numeric value in the input file as well as a seemingly invalid string value: `_networkx_list_start`. It seems to be some kind of a conversion error; for instance, the second node of the graph has attributes like these:

```
    members "_networkx_list_start"
    members 0
    seqIDs "_networkx_list_start"
    seqIDs "0_0_13"
    [...]
    lengths "_networkx_list_start"
    lengths 939
```

I took the input file, removed all lines containing `_networkx_list_start` and all lines containing `longCentroidID`, and the remaining file is read correctly by igraph on Ubuntu Linux (20.04) now. I'll file an issue in igraph/igraph for the crash itself and close this one.

**Comment by ntamas** [comment]
Issue filed for the C core at https://github.com/igraph/igraph/issues/1805 - feel free to follow up on the issue there.

**Comment by ntamas** [comment]
It turns out that this is already fixed in the C core; the CRAN version has not been updated yet to incorporate the fix. @vtraag , you have been experimenting in the past with updating  the R interface to a more recent version of the igraph C core (I think in the 0.8.x branch) and I can see that the `dev` branch is several commits ahead of the `cran` branch. What would it take to push the current `dev` branch as a release to CRAN?

@samlipworth In the meanwhile, you can try installing the development version as follows:

```
install.package("remotes")
remotes::install_github("igraph/rigraph@master")
```

This will compile the master branch on your machine, which should be able to read your original GML file successfully. For attributes having multiple values, it will use the last value from the file, promoting integers to strings if there is at least one string value for the attribute.

**Comment by samlipworth** [comment]
Thanks so much for all your efforts on this @ntamas - hugely appreciated. I will give installing the dev version a go.

**Comment by samlipworth** [comment]
Very pleased to report that this worked - thanks again.

**Comment by vtraag** [comment]
> @vtraag , you have been experimenting in the past with updating the R interface to a more recent version of the igraph C core (I think in the 0.8.x branch)

Yes, it is currently up to version 0.8.5 in the `dev` branch. I have not yet updated it to the 0.9 branch, because the build system changed (from autotools to CMake), and that will probably require more effort to update the R interface (although the build system of the R package itself remains unchanged).

> I can see that the `dev` branch is several commits ahead of the `cran` branch

Indeed all changes to the `cran` branch are merged in the `dev` branch. In principle, we can remove the `cran` branch, however, the most recent release (1.2.6) was made by @gaborcsardi from the `cran` branch, which is the reason it is still there. This was also discussed in https://github.com/igraph/rigraph/issues/434.

> What would it take to push the current `dev` branch as a release to CRAN?

In principle it would be ready to go. However, I wanted to first make sure that all additions/improvements from the C core would be available to the R interface, otherwise the benefit of a new release is more marginal. I hadn't yet gotten around to do that. Once that is done, we can in principle push a new release to CRAN.
