### ISSUE TITLE
same data from graph_from_edgelist / graph_from_dataframe, but not identical 

### ISSUE THREAD

**Issue by youngjinkim81** [igraph/rigraph#481]
edgelist <- matrix(
                   c(1, 5,
                     2, 5,
                     2, 6, 
                     3, 5,
                     4, 5,
                     5, 7,
                     5, 8,
                     5, 9,
                     5, 10,
                     7, 8,
                     7, 9,
                     7, 10,
                     8, 7,
                     8, 9,
                     8, 10,
                     9, 7,
                     9, 8,
                     9, 10,
                     10, 7,
                     10, 8,
                     10, 9), 
                   ncol = 2, byrow = TRUE)

g2 <- graph_from_edgelist(edgelist, directed = TRUE)
g3 <- graph_from_data_frame(edgelist, directed = TRUE)

identical_graphs(g2, g3) 
**[1] FALSE**

I don't understand.. why? 
It looks like error

**Comment by ntamas** [comment]
`identical_graphs()` checks whether the R _representation_ of two graphs is identical. This includes things like edge ordering. Chances are that `graph_from_data_frame()` adds edges in a different order than `graph_from_edgelist()` and that's why you get a negative result. If you want to know whether two graphs are _isomorphic_, use `isomorphic()` instead.
