### ISSUE TITLE
Failed to install `igraph_1.2.11` in `R 4.1.2`

### ISSUE THREAD

**Issue by YulongNiu** [igraph/rigraph#507]
**Describe the bug**

Failed to install `igraph_1.2.11`. Erroneous messages appear:

```
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:642:26: error: no template named 'numeric_limits'
    bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
                         ^
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:642:60: error: no template named 'numeric_limits'
    bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits),
                                                           ^
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:643:18: error: no template named 'numeric_limits'
    int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)>
                 ^
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:643:50: error: no template named 'numeric_limits'
    int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)>
                                                 ^
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:648:17: error: no template named 'numeric_limits'
  static_assert(numeric_limits<_FloatT>::radix == 2, "FloatT has incorrect radix");
                ^
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:651:25: error: no template named 'numeric_limits'
  return _FloatBigger ? numeric_limits<_IntT>::max() :  (numeric_limits<_IntT>::max() >> _Bits << _Bits);
                        ^
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:651:58: error: no template named 'numeric_limits'
  return _FloatBigger ? numeric_limits<_IntT>::max() :  (numeric_limits<_IntT>::max() >> _Bits << _Bits);
                                                         ^
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:661:16: error: no template named 'numeric_limits'
  using _Lim = numeric_limits<_IntT>;
               ^
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:664:12: error: use of undeclared identifier '_Lim'
    return _Lim::max();
           ^
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:665:21: error: use of undeclared identifier '_Lim'
  } else if (__r <= _Lim::lowest()) {
                    ^
/usr/local/opt/llvm/bin/../include/c++/v1/cmath:666:12: error: use of undeclared identifier '_Lim'
    return _Lim::min();
           ^
215 warnings and 11 errors generated.
make: *** [gengraph_degree_sequence.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/usr/local/lib/R/4.1/site-library/igraph’
* restoring previous ‘/usr/local/lib/R/4.1/site-library/igraph’
```

**To reproduce**

Install`igraph_1.2.11` in R

```
install.package('igraph')
```

**Version information**

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin21.1.0 (64-bit)
Running under: macOS Monterey 12.1

Matrix products: default
BLAS:   /usr/local/Cellar/openblas/0.3.19/lib/libopenblasp-r0.3.19.dylib
LAPACK: /usr/local/Cellar/r/4.1.2/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.1.2 tools_4.1.2
```

**Comment by ntamas** [comment]
Your installation is probably broken; `numeric_limits` is a [standardized C++ class template](https://en.cppreference.com/w/cpp/types/numeric_limits), so if your compiler does not find it, it indicates a deeper problem with the configuration of your system and has nothing to do with igraph.

Similar problems were reported in the context of other packages in the past (e.g., [this one](https://github.com/explosion/thinc/issues/219) ). Check your compiler settings and include paths; check the output of `brew doctor` and fix any problems that seem relevant.

Also, note that the reason why the system wants to compile igraph is because you are using R from Homebrew. Consider installing the official R package for macOS; CRAN provides precompiled binaries for igraph on macOS so you would not need to compile igraph from source.

**Comment by YulongNiu** [comment]
Thank you @ntamas. Though the options like `rm /usr/local/include/` did not work for me, I am glad to confirm from you that the problem is not original from `rigraph`. I will try to figure it out.

**Comment by ntamas** [comment]
Try compiling a basic C++ program that uses `std::numeric_limits<>` for something. If it works, then the problem is probably in additional compiler switches that the build process passes to the compiler. Also look for stale `~/.R/Makevars` files or similar things that might affect the compiler options. You can also try reinstalling the XCode Command Line Tools.

**Comment by YulongNiu** [comment]
I removed `R` installed from homebrew, then installed [R for Mac](https://cran.r-project.org/bin/macosx/). I can install `igraph_1.2.11`in R for Mac. 

My suggestion is do not remove `/usr/local/include/` as [suggested](https://github.com/explosion/thinc/issues/219#issuecomment-574247098), because lots applications installed by homebrew depend header files in `/usr/local/include/` and reinstall `brew list | xargs brew reinstall` is slow.
