### ISSUE TITLE
Message "graph was created by an old(er) igraph version", but it actually wasn't

### ISSUE THREAD

**Issue by bockthom** [igraph/rigraph#512]
**Description of the bug**
I often create huge networks and then store them to a binary R data file using R's `save` function, to continue using the network later via loading it using R's `load` function. This works quite well for several years, but currently, when accessing the network after loading it, I get the warning message
```
This graph was created by an old(er) igraph version.
  Call upgrade_graph() on it to use with the current igraph version
  For now we convert it on the fly...
```
And then it takes many minutes for converting it and uses way more RAM than need to build the network... and whenever accessing any attribute of the network again, it again starts converting it on the fly...

**To reproduce**
The current environment in which this weird behavior occurs:

R version: 4.1.2
Platform: x86_64-pc-linux-gnu (64-bit) running under Debian GNU/Linux 11 (bullseye)

igraph version: I tried both 1.2.6 and 1.2.11 and the error occurs in both versions. So, when creating a network and saving it under 1.2.6, the behavior occurs when loading the same network under 1.2.6. And when creating the network and saving the network under 1.2.11, the behavior occurs when loading this network under 1.2.11. Therefore, I assume that this might be not dependent on the igraph version, but maybe dependent on the R version, as in pervious R versions and igraph 1.2.6, the problem did not occur yet.

To provide a few more details:

Just assume that I save a new created graph `graph` to file:
```R
save(graph)
[...]
load(graph)
```
When I then call `graph_version()`, I get `"0.8.0"`.
But when I then call `graph_version(graph)`, I get `"0.4.0"`.
How can it happen that the stored/loaded version number is lower than the current version?

As I am not sure what this graph versioning numbers point to and where they are determined from, I would be glad if someone could have a look at this problem to circumvent that newly created graphs get converted ever and ever again...
Thanks in advance!

---
And just a short side question in the end: Can you already estimate when you will release a new version of rigraph? I'll imagine that you won't give promises as nobody knows which bugs will appear prior to your planned release and how much time bug fixing may need, but is it rather a question of weeks or a question of months?

**Comment by szhorvat** [comment]
> Can you already estimate when you will release a new version of rigraph?

You can already install the development version (which will become 1.3), but you need to compile it yourself. That's easier on Linux, on other platforms you may need to install the R development tools first. Instructions are here: https://github.com/igraph/rigraph/#installation Feedback about this version is very welcome.

----

As for the graph versioning issue, some of our contributors unavailable at the moment, so it may take until March to look into it. Rest assure it won't be ignored though.

**Comment by ntamas** [comment]
> I am not sure what this graph versioning numbers point to and where they are determined from

This is the function in the R-to-C glue code that determines the version number: https://github.com/igraph/rigraph/blob/dev/tools/stimulus/rinterface_extra.c#L264

Essentially, the version number is 0.4.0 for "old" igraph graphs (as far as I know this format has not been in use for several years now), and 0.8.0 for recent versions. The two are generally distinguished by the structure of the graph object itself. If you call `unclass(g)`, you will see that an igraph graph is essentially a list of length 10, where the first 9 items store basic info about the graph and the 10th item is an R environment with metadata. Inspecting the contents of the environment reveals the item that stores the version number:

```
> ls(unclass(g)[[10]], all.names=T)
[1] ".__igraph_version__." "me"                   "myid"
> unclass(g)[[10]]$.__igraph_version__.
[1] "0.8.0"
```

Note that the `graph_version()` functions first looks at the graph object and checks whether 1) it is a list, 2) its length is 10 and 3) the last element is an environment. If any of these conditions fail, it will return 0.4.0 as the version number. The question is how this can happen in your case if you are creating graphs with igraph. Are you doing anything special with your graphs that would involve unclassing it and modifying its internal structure? What does `unclass(g)` return for your graph?

---

As for the new version: our aim is to bring the R interface up-to-date with the C core. The current R interface is based on igraph 0.8.x, while the C core is now at igraph 0.9.x. There are a few items on my TODO list that involve adding new functionality that appeared in igraph 0.9.x, and there's also the [backlog for the next release](https://github.com/igraph/rigraph/milestone/2). I'd like to finish these before making a new release, but currently I'm tied up in other stuff in the C core and I probably won't be able to get back to working on R-igraph before mid-March. However, if you are running into issues with the R interface and you find that these are already fixed in the development branch, let me know and I'll see what we can do to release a new version of R-igraph earlier.

**Comment by bockthom** [comment]
> Are you doing anything special with your graphs that would involve unclassing it and modifying its internal structure? What does `unclass(g)` return for your graph?

Thank you very much, your explanations helped me to identify the problem. Indeed, something special happened which I was not intended to do. So, we can close this issue, I guess. But thanks for your help, without your help I never would have found out what was going on...

For the sake of completeness, here a short explanation what I did which ended up in this weird versioning issue:

I created a named list of different graphs created with igraph (`graph1`, `graph2`, etc.), such like that:
```R
l = list()
[...]
l[["name1"]] = graph1
[...]
l[["name2"]] = graph2
[...]
```
Unfortunately, one of the names was broken and was a vector of names instead:
```R
l[[c("name2", "name3")]] = graph3
```
So, `graph3` was stored as a named element attached to `graph2` and, therefore `unclass(l[["name2"]])` does not contain a list of length 10 but also an additionally attached graph object. And this broke the `graph_version(...)` call on `l[["name2"]]`, as it contained `graph2` and `graph3` attached to it as a named element. So, I only need to fix the names such that it is a single character string instead of a vector of multiple strings...
