### ISSUE TITLE
shortest_paths() adds NA into predecessor vector

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#523]
**Describe the bug**

This is a similar issue to #522 and #186.

`shortest_paths()` can return `predecessor` vertex sequences with `NA`s in them, which then cause problems.

The documentation states:

> `predecessors` Logical scalar, whether to return the predecessor vertex for each vertex. The predecessor of vertex i in the tree is the vertex from which vertex i was reached. **The predecessor of the start vertex (in the from argument) is itself by definition.** **If the predecessor is zero, it means that the given vertex was not reached from the source during the search.** Note that the search terminates if all the vertices in to are reached. 

There is some inconsistency here: 

  - The predecessor of the root being itself is a strange, and IMO bad, decision. This practically represents a loop, making the predecessor vector invalid. We have an issue and PR for the C core about the representation of trees, and a straightforward implementation of loop detection (i.e. validation) would reject such a vector. https://github.com/igraph/igraph/issues/1880
  - Unreachable vertices are claimed to get `0`, which is not a valid vertex ID, so it can't be part of a vertex sequence. However, in practice they get `NA`, which then causes all the same issue as in #522.

**To reproduce**

```
g <- make_ring(4) + make_ring(4)
res <- shortest_paths(g, 1, predecessors=T)$predecessors
```

See #522 for the rest, e.g.

```
> is.na(res[5])
Error in simple_vs_index(x, args[[1]]$expr) : Unknown vertex selected
```

**Version information**
 
1.3.0 as well as earlier.

**Comment by szhorvat** [comment]
Adding to 1.3.1 milestone because #186 was fixed for 1.3.1 and we want some consistency.

**Comment by szhorvat** [comment]
I have no problem with using `NA`s for as long as they don't trigger errors on every corner.

**Comment by ntamas** [comment]
I've looked into this a bit. Actually, `simple_vs_index()` has an argument named `na_ok`, and it can be used to coerce `simple_vs_index()` into handling `NA`s. The problem is that `simple_vs_index()` is an internal function, and we interact with it via `[.igraph.vs` instead and the implementation of `[.igraph.vs` did not forward the `na_ok` argument correctly. Now the following syntax works on my computer after fixing this:

```
> g <- make_ring(4) + make_ring(4)
> res <- shortest_paths(g, 1, predecessors=T)$predecessors
> res[5]
Error in simple_vs_index(x, args[[1]]$expr, na_ok) :
  Unknown vertex selected
> res[5, na_ok=T]
+ 1/8 vertex, from f8a2e56:
[1] NA
>
```

Note that you still need to explicitly define that you are okay with NA values after indexing. Is this satisfactory for you? I guess I can't do much more than this before the 1.3.2 release; otherwise I'd basically need to store for each created `igraph.vs` object whether it was created with `na_ok = T` so I'd know that indexing this further should pass `na_ok = T` to `simple_vs_index`. (And it would also mean that not all `igraph.vs` objects have equal capabiltiies; those that were created from functions that can potentially return NA items are different from those that were created from functions that do not return NA items).

**Comment by ntamas** [comment]
The implementation of `[.igraph.vs` was fixed so it now forwards `na_ok` into internal calls as needed. The related commit is d88657c7
