### ISSUE TITLE
Missing usage lines for is_connected, count_components

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#525]
There is no "Usage" line for `is_connected` and `count_components` in the docs. I'm not sure how the usage line is generated, so some help in fixing this would be appreciated. To see the issue, try `?is_connected` and see the doc page that comes up.

**Comment by ntamas** [comment]
eb549fa1 fixes this. There could be lots of these, though; it looks like it happens when there are functions whose documentation chunk refers to other functions in `@aliases` and some of those functions are auto-generated in `R/auto.R`. Not sure why the alternative approach in this commit works and the original doesn't, but it seems to work this way.
