### ISSUE TITLE
igraph 1.3.x backward compatibility on Windows

### ISSUE THREAD

**Issue by jobeid** [igraph/rigraph#534]
**Describe the bug**
When calling `library(dm)`, I get an error dialog:

```
rsession-utf8.exe - Entry Point Not Found

The procedure entry point quadmath_snprintf could not be located in the dynamic link library C:\Users\USERNAME\AppData\Local\R\win-library\4.2\igraph\libs\x64\igraph.dll.
```

Reinstalling igraph v1.2 fixes the problem, but I presume this will need to be addressed backward compatibility.
Is anyone else experiencing this issue?

**To reproduce**

Steps or minimal example code to reproduce the problem.

Running R 4.2 or R 4.1.3, on Windows 10. dm version 2.8, igraph version 1.3.x
Open a new blank project in rstudio (latest version). Make sure you have dm package installed.
run this line: 

```
library(dm)
```

**Version information**
Which version of igraph are you using?
Version 1.3.0 or 1.3.1

**Comment by ntamas** [comment]
There isn't a single call in the entire igraph codebase to `quadmath_snprintf` so I wonder where the symbol is coming from at all.

Do you also have this problem if you simply try to load the `igraph` library with `library(igraph)`, without touching `dm` at all?

**Comment by szhorvat** [comment]
For completeness, it's good to link back here: https://github.com/cynkra/dm/issues/989

**Comment by szhorvat** [comment]
Possible hints:

This symbol is from GCC's 128-bit floating point implementation. The quadmath library is typically linked to by code compiled with `gfortran`.

**Comment by ntamas** [comment]
I cannot reproduce this on Widnows with R 4.2.0; `igraph` and `dm` both installed from binaries from CRAN. Can it be the case that `igraph` was compiled from source on this machine?

**Comment by jobeid** [comment]
> There isn't a single call in the entire igraph codebase to `quadmath_snprintf` so I wonder where the symbol is coming from at all.
> 
> Do you also have this problem if you simply try to load the `igraph` library with `library(igraph)`, without touching `dm` at all?

**Comment by ntamas** [comment]
Hmm, no we don't, but I have recently received an email from someone who reported that previous versions of igraph supported using it with Intel's MKL libraries and it stopped working in igraph 1.3.0. I wonder whether this is the same issue.

**Comment by jobeid** [comment]
> issue

Probably. Was that under Windows? If needed, I can test in that environment.

**Comment by ntamas** [comment]
Most likely Windows, but I have no further information yet. If we want to test this on our end, is it as simple as installing Microsoft R Open, and then running `install.packages("igraph")` followed by `library(igraph)`?

**Comment by szhorvat** [comment]
Did you compile igraph from sources, or did you use the binaries from CRAN?

**Comment by jobeid** [comment]
Fyi, in Microsoft R Open (MRO), you have to specify the repo, otherwise it will install from the MRO repo (currently, that of v4.02), which has an older version of igraph (i think it was v1.2.5). In any case, you can run:

install.packages('igraph', repos='http://cran.us.r-project.org')

Then choose not to compile. Now igraph v1.3 is installed in MRO with r v4.02

Now running library(igraph) results in the error. Details:
Error: package or namespace load failed for ‘igraph’ in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Users/USERNAME/Documents/R/win-library/4.0/igraph/libs/x64/igraph.dll':
  LoadLibrary failure:  The specified procedure could not be found.
In addition: Warning message:
package ‘igraph’ was built under R version 4.0.5 

The windows error dialog shows:
The procedure entry point quadmath_snprintf could not be located in the dynamic link library C:\Users\USERNAME\Documents\R\win-library\4.0\igraph\libs\x64\igraph.dll.

**Comment by jobeid** [comment]
> Did you compile igraph from sources, or did you use the binaries from CRAN?

Did not compile from source.

**Comment by szhorvat** [comment]
How did you revert to igraph 1.2 without compiling from source? Did you use 1.2.11 or another 1.2.x version?

**Comment by jobeid** [comment]
> How did you revert to igraph 1.2 without compiling from source? Did you use 1.2.11 or another 1.2.x version?

I have a zipped copy saved, since I need it for compatibility. All I have to do is delete the contents of `R\win-library\4.x\igraph` then copy the contents of the old package in there. Let me know if you need the zipped copy.

**Comment by szhorvat** [comment]
> So the problem was that I had a blas library compiled under MRO (Microsoft's Rblas.dll). After I replaced that back to the cran r version, the problem was resolved (although i'm back to non-MKL rblas).

Can you let us know:

 - Which R distribution are you using, i.e. where did you get R? Did you download it from https://www.r-project.org/ or somewhere else?
 - What exactly did you do to try to use the MKL, and what did you base it on (any references)?

**Comment by jobeid** [comment]
> Can you let us know:
> 
>     * Which R distribution are you using, i.e. where did you get R? Did you download it from https://www.r-project.org/ or somewhere else?

Currently using r4.2 from https://cran.r-project.org/bin/windows/base/

But I also have older versions, including MRO v4.02 from https://mran.microsoft.com/open

>     * What exactly did you do to try to use the MKL, and what did you base it on (any references)?

I have used the MKL rblas dlls from MRO with cran R versions. Ref: https://stackoverflow.com/questions/38090206/linking-intels-math-kernel-library-mkl-to-r-on-windows , specifically the comment on Mar 17, 2017 by Tom Wenseleers.

**Comment by ntamas** [comment]
I don't think that simply replacing DLLs is supposed to work with arbitrary R versions, even if it worked in the past. @szhorvat did some more debugging with Dependency Walker and it turns out that `quadmath_snprintf` is present in R's official `Rlapack.dll`, and for some reason `igraph.dll` needs it (I guess it is simply to support printing variables of type `__float128` from printf-style functions). If you replace `Rlapack.dll` from another version that does not provide `quadmath_snprintf`, you are likely to get this error.

For what it's worth, `Rlapack.dll` in older versions of R did not include `quadmath_snprintf` either, so most likely this is the root cause. Essentially, you take `igraph.dll` that is compiled for a newer version of R where `Rlapack.dll` provides `quadmath_snprintf` (due to its dependence on `gfortran`, which is usually the library that brings in all the quadmath stuff), and then you try to use that with an alternative version of `Rlapack.dll` that was built in a time when it did not provide `quadmath_snprintf` yet (maybe because it was not compiled with `gfortran`, or it was compiled with an older version of `gfortran`, or with different compiler switches).

**Comment by szhorvat** [comment]
I expect that this breakage is not due to a change in igraph, but is a consequence of 1.3.1 being built with newer R and RTools.

Ultimately, replacing DLLs is a fragile hack that always carries a risk of breakage. To ensure compatibility, the replacement DLLs should come from the same R version compiled with the same toolchain (RTools), which is not the case here.

----

That said, I do wonder:

  - Why does igraph use `quadpath_snprintf` only on Windows and not other platforms? gfortran must be inserting the call to this function, but why? We do not use quad-precision numbers explicitly.
  - Do other packages that have Fortran components and use LAPACK also suffer from the same? I checked RxODE and it seems to have no reference to `quadpath_snprintf`. So Fortran + LAPACK are not enough to trigger it.

This problem may be extremely specific, possibly only affecting igraph, but that does not mean that it doesn't come from R itself (remember that `quadpath_snprintf` appeared in `Rlapack.dll` recently). However, if we asked R people about it, I expect the answer would be that replacing DLLs is a fragile an unsupported hack.

**Comment by xiaoying201355** [comment]
> > How did you revert to igraph 1.2 without compiling from source? Did you use 1.2.11 or another 1.2.x version?
> 
> I have a zipped copy saved, since I need it for compatibility. All I have to do is delete the contents of `R\win-library\4.x\igraph` then copy the contents of the old package in there. Let me know if you need the zipped copy.

Hello, I had the same problem, could you please send me the zipped copy to ying.zhang@osumc.edu, thank you very much!
