### ISSUE TITLE
Add an igraph class to the format of write_graph and read_graph

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#544]
**What is the feature or improvement you would like to see?**
Add an igraph class to the format of write_graph and read_graph.

    format = c("igraph", "edgelist", "pajek", "ncol", "lgl", "graphml", "dimacs", "gml", "dot",  "leda"),

The output of write_graph(g, format="igraph) becomes identical to the output of `str(g)`.
read_graph() becomes the inverse of write_graph().

**Remark**
Due to the discussions below, I recommend using the format `readRDS() ` instead of `str()`.
An alternative is to use toString(). And/or implement fromString().

**Use cases for the feature**
Allows igraph objects to be moved more accurately than with non-native formats.

**References**
List any relevant references (papers or books describing relevant algorithms).

**Comment by szhorvat** [comment]
If you are looking to save igraph graphs in unaltered form, you can use `saveRDS` and `readRDS`. Is there anything that you are looking for that these do not already provide?

**Comment by clpippel** [comment]
It would be nice if I could send (pipe) the output to a string and read it back.

 I try to avoid the file system if possible. I am a recreational user. I want to keep it as simple as possible.

What I'm trying to achieve is to serialize an (igraph) object to a string and reverse the process.

**Comment by clpippel** [comment]
I tried saveRDS. The format of str(g) is more readable and concise.

**Comment by ntamas** [comment]
> It would be nice if I could send (pipe) the output to a string and read it back.

You can use a `textConnection`:

```
conn <- textConnection("graph", "w")
saveRDS(g, conn, ascii=TRUE)
close(conn)
print(graph)
```

As for `str(g)`, I'm not 100% sure it would always produce a representation that could be used to reproduce the original graph object unambiguously. An igraph graph is essentially a list of 10 objects; objects 1 to 8 represent the internal graph structure, object 9 is the attribute table, and object 10 is a special R environment that is used to store internal info about the graph. For me it seems like `str(g)` does not seem to preserve the environment.

The internal representation of an igraph graph has changed over time, and we reserve the right to change it in the future. The environment itself contains a hidden member named `.__igraph_version__.`, which is a version number of the graph structure, and it is used by igraph to "upgrade" the internal structure when the graph is restored from an earlier saved version. If you don't serialize `.__igraph_version__.`, we have no way of knowing what the internal structure means and whether it should be upgraded to the current igraph representation. That's why we suggest using `saveRDS` and `readRDS`, as these are meant to save R objects in a form where it is guaranteed that all information is saved and restored. `str()` does not guarantee that.

**Comment by clpippel** [comment]
I am convinced using str() is not a good idea. My new suggestion is to use the format of readRDS, writeRDS.
