### ISSUE TITLE
Plot throws "Error in groups(x)[[i]] : subscript out of bounds"

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#554]
**Describe the bug**
Plot throws "Error in groups(x)[[i]] : subscript out of bounds"

**To reproduce**
```
g <- make_empty_graph(1L)
clu <- cluster_spinglass(g)
clu
plot(g, mark.groups=clu)
```
Output:
```
IGRAPH clustering spinglass, groups: 2, mod: NaN
+ groups:
  $`2`
  [1] 1
Error in groups(x)[[i]] : subscript out of bounds
```
If you are unsure, feel free to add your issue here - we will transfer it to
the main [igraph repo](https://github.com/igraph/igraph) if the root cause is
in the C core of igraph.

**Version information**
Which version of igraph are you using?
 A: 1.3.3

**Comment by clpippel** [comment]
Observe that:
```
g <- make_de_bruijn_graph(2,4)
cluster_walktrap(g, steps=4)
plot(g, mark.groups=clu)
```
produces error:
```
Error in simple_vs_index(x, lazy_eval(args[[1]]), na_ok) : 
  Unknown vertex selected
```

**Comment by ntamas** [comment]
It is supposed to be `plot(g, mark.groups = communities(clu))`; see [this page](https://igraph.org/r/doc/communities.html), which contains an example call of `plot()` with a valid `mark.groups` argument. Basically, `mark.groups` needs a list of vertex lists, and `clu` is not simply a list of vertex lists but also contains additional properties that throw igraph off track.

**Comment by clpippel** [comment]
Thanks.   I missed that. However the difference between clu and communities(clu) is not straightforward:
```
> clu
IGRAPH clustering spinglass, groups: 2, mod: NaN
+ groups:
  $`2`
  [1] 1
  
> communities(clu)
$`2`
[1] 1
```
Shouldn't mark.groups be testing for the correct input then, that is: `not a list of vertex id vectors`?

**Comment by ntamas** [comment]
I'm not an R expert so I might be wrong her, but I think that the problem is that it's hard to detect reliably what's "just" a list in R and what is something that looks like a list but is not a list. For instance:

```
> stuff <- list()
> is.list(stuff)
[1] TRUE
> class(stuff)
[1] "list"
```

but also:

```
> g <- make_graph("zachary")
> is.list(g)
[1] TRUE
> class(g)
[1] "igraph"
> clu <- cluster_leiden(g)
> is.list(clu)
[1] TRUE
> class(g)
[1] "communities"
```

So I can't simply use `is.list()` to distinguish between lists and non-lists; I'd need to do something like `class(x) == "list"`, but then I'd be disallowing any custom user-made lists of vertex ID vectors where the user wrapped the list in some custom class. Maybe something like `inherits(x, "list")` would work, but here I'm in unfamiliar territory as I'm not using R's class system on a daily basis to judge whether this would be appropriate or not. (And even if I managed to decide whether the input is a list or not a list, how should I attempt to decide whether the members are genuine vertex ID vectors or just random vectors of numbers that happen to look like vertex IDs?).

An alternative way would be special-casing the handling of `communities` objects (i.e. objects where `inherits(x, "communities")` such that they are automatically passed through the `communities()` function when handling `mark.groups`, but there are tons of other places in the library where we could make similar attempts to try and guess what the user could have meant, and it's hard to draw a line where it's not worth doing it any more.

All in all, checking for exact types in a dynamic language like R is hard. Specific proposals about how to do a type validation here are welcome.

**Comment by clpippel** [comment]
I plan to look into it. Might be an idea to reopen this issue.

**Comment by clpippel** [comment]
You might consider performing an appropriate conversion, after the test for a numeric vector (after line 70)

`if (is(mark.groups, "communities")) mark.groups <- communities(mark.groups)`

And update the docs accordingly.

**Comment by clpippel** [comment]
I do not think there is something wrong with the plot procedure. Consider for example the output of spinglass:
```
g <- make_empty_graph(1L)
clu <- cluster_spinglass(g)
print.default(clu)
```
Output:
```
$membership
[1] 2

$csize
numeric(0)

$modularity
[1] NaN

$temperature
[1] 0.01

$algorithm
[1] "spinglass"

$vcount
[1] 1

attr(,"class")
[1] "communities"
```
The contents of $membership (2) seems wrong because there is no vertex 2.
And $csize  should be 1.

An additional problem is that this situation is not handled correctly by the special length function.
length(clu) produces:` [1] 2`. This should be 1.

**Comment by clpippel** [comment]
The conversion I suggested isn't necessarily required because mark.groups[[g]] magically reads from the groups.

**Comment by clpippel** [comment]
However, it shields the plot in the rare case of corrupt community structures.

**Comment by ntamas** [comment]
> I do not think there is something wrong with the plot.igraph procedure. Consider for example the output of spinglass:

For the record, this was reported separately and it is now fixed (just adding this comment here so I don't forget it).

> You might consider performing an appropriate conversion, after the test for a numeric vector

Thanks, this is now done in fbbfa7c0
