### ISSUE TITLE
Rename master to main?

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#611]
This fits with the DEI topic. :smile_cat:

**Comment by szhorvat** [comment]
I strongly believe that in order for igraph to be a project where everyone can work together, the discussion here must have one clear focus: developing a network analysis library. This is what keeps things going smoothly. 

There is a right place for everything, and this is not the place for making political statements, which this effectively is.  I want this to be a place where people can work together even if their countries are at war with each other. This is achievable if we keep the focus on what is relevant for the project, and stay away from anything that elicits unproductive debate, especially alignment with specific political movements of specific countries.

**Comment by ntamas** [comment]
I don't think it's a political statement. It's a recognition that in certain countries / communities, words like `master` and `slave` might be controversial, while `main` is not. I don't give a sh*t about politics.

Note that Git and Github has already switched to using `main` instead of `master` as the default branch name. Doing the rename on our side has nearly zero cost to us (apart from maybe ~2 mins of inconvenience to rename our local checkout branches), so I don't have any objetions.

**Comment by vtraag** [comment]
Fully agree with @ntamas here.

There's been a switch to using `main` as the default in the community already a while ago, and I think it's perfectly reasonably for igraph to follow suit. We have similarly made changes in the code, preferring more neutral terminology, using for instance parent instead of father (although this is apparently not done everywhere yet).

I propose to switch from using the `master` branch to `main` in all igraph repositories, in order to avoid confusion.

**Comment by iosonofabio** [comment]
Let's just do it, it's a big deal for part of the community and basically zero chat for the rest 😉

I love zero cost changes

Cheers,
Fabio

**Comment by krlmlr** [comment]
Thanks for considering.

There's an organization-wide setting on GitHub that allows defining the name of the main branch for new repositories, too. The corresponding local Git config is:

```sh
git config --global init.defaultBranch main
```

This is useful if you create a repository locally first and then push it to GitHub.

**Comment by ntamas** [comment]
In the R repository, I think we should simply wait until we are ready to get rid of the two-branch setup; we can then rename `dev` into `main` and delete `master`.

Right now probably there's still something missing from `dev` as `remotes::install_github("igraph/rigraph@dev")` prints an HTTP 404 error.

**Comment by krlmlr** [comment]
Just to confirm: are there any unresolved action items here?

**Comment by ntamas** [comment]
I don't think so.
