### ISSUE TITLE
"Error in try_fetch(utils::getFromNamespace(algorithm, "igraph"), error = function(cnd) { : could not find function "try_fetch" "

### ISSUE THREAD

**Issue by MANZHAOHUI** [igraph/rigraph#649]
**Describe the bug**
when I was using clustree, I constantly got this error despite my reinstalling igraph. 

**To reproduce**
cluster_tree <- clustree(combined.int.clustree,prefix = "integrated_snn_res.") combined.int.clustree is a seurat single cell RNA object.

**Version information**
 ‘1.2.6’

**Comment by ntamas** [comment]
Transferred to the repo of the R interface.

I'm still quite convinced that this is not an igraph issue, but in case it is, we would need a short, self-contained, reproducible example that triggers the error in our environment. We cannot test the code that you have posted because we don't have that particular `combined.int.clustree` object.
