### ISSUE TITLE
Settings for GitHub Pages website

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#654]
The pkgdown GitHub Actions workflow successfully deploys a pkgdown website to the gh-pages branch. I'd suggest

- setting this branch as source for a GitHub Pages website.
- setting a redirect from http://igraph.org/r to that website.
OR
- using a fancier setup to put the website contained in the gh-pages branch, wherever http://igraph.org/r source is.

In any case once a location is decided the URL to the pkgdown website needs to be stored in two places:
- DESCRIPTION file https://github.com/igraph/rigraph/blob/4ae056eb414728313210085a5109842359163101/DESCRIPTION#L34,
- pkgdown configuration file. https://github.com/igraph/rigraph/blob/4ae056eb414728313210085a5109842359163101/_pkgdown.yml#L1

**Comment by ntamas** [comment]
Site deployed to https://igraph.github.io/rigraph/

I'll deal with the redirects once we are okay with the site content.

**Comment by iosonofabio** [comment]
Looks awesome! A few QS:

- Could we have a link to the vignette on the homepage, possibly one for each language?
- installation is explained three times: homepage, vignette, troubleshooting article. Do you guys think we could streamline it?

**Comment by szhorvat** [comment]
The troubleshooting page was put together based on actual issues people had. I'd prefer not to remove information from it.

No comments on the rest.

**Comment by maelle** [comment]
@iosonofabio 

> Could we have a link to the vignette on the homepage, possibly one for each language?

See #651 for the corresponding pkgdown configuration.

> installation is explained three times: homepage, vignette, troubleshooting article. Do you guys think we could streamline it?

Part of it could be shared, via "R Markdown fragments" so that it'd still appear in all pages but the source wouldn't be duplicated, see https://www.garrickadenbuie.com/blog/dry-vignette-and-readme/

**Comment by maelle** [comment]
@krlmlr @ntamas should https://github.com/igraph/rigraph/blob/6bff8652a9af6fcbd9748805b5d2809bc8785fb4/DESCRIPTION#L34 be amended before the CRAN release, to point to this GitHub repository and to http://igraph.org/r (this way, when the redirect is set up, the CRAN page already links to the right website)?

**Comment by szhorvat** [comment]
> Site deployed to https://igraph.github.io/rigraph/

The new website will still live at https://igraph.org/r/, right? Let us try not to fragment the domains if possible.

Moving the py-igraph docs to https://igraph.readthedocs.io was not ideal, and currently most people still check (and link to) https://igraph.org/python/. However, in that case it was _necessary_ to change the domain in order to use the _Read the Docs_ infrastructure (is this correct @iosonofabio ?). In this case a domain change is not necessary, is it?

**Comment by maelle** [comment]
> The new website will still live at [igraph.org/r](https://igraph.org/r/), right? Let us try not to fragment the domains if possible.

The workflow could be changed (deploying to GitHub pages was the easiest setup to start with, but not necessary), or there could just be some sort of redirect?

Note the website source lives in https://github.com/igraph/rigraph/tree/gh-pages, maybe that can "easily" be hooked into the infrastructure for igraph.org?

**Comment by ntamas** [comment]
> However, in that case it was necessary to change the domain in order to use the Read the Docs infrastructure (is this correct @iosonofabio ?)

Read the Docs allows one to use [custom domains](https://docs.readthedocs.io/en/stable/custom-domains.html) but not custom folders inside an existing site. So, we could redirect python.igraph.org to igraph.readthedocs.io but we cannot redirect igraph.org/python . Well, actually, we _could_, if we had full control of the webserver on igraph.org, because in that case we could set up an Nginx reverse proxy that forwards requests to igraph.readthedocs.io after stripping the /python prefix, but it would also need to take care of fixing any absolute URLs returned by igraph.readthedocs.io by re-adding the /python prefix. So it's possible, but it's messy, and I have no issues with hosting the docs on readthedocs.io as long as people can find it.

In the case of pkgdown, there _might_ be an easy way but I'm not sure how it would look like yet. igraph.org is basically a huge Jekyll site where most of the Jekyll source files are built by an ugly and complicated makefile. The R part is actually the cleanest part of that makefile :) We will probably need to inject the pkgdown infrastructure there, but if we want igraph.org to automatically update after commits, that would mean coordinating between Github Actions in different repos and I'm afraid this is also heading into a direction where we implement additional complexity just for the sake of not having to redirect users to a domain outside igraph.org.

Maybe we could settle on `r.igraph.org` as a subdomain and configure it as a custom subdomain for Github Pages, and do the same with Python so we could have `python.igraph.org` for the Read the Docs page? That would be a reasonable compromise for me where we can keep the current workflow (which seems to be mostly hassle-free) while we could still keep all the pages under the same umbrella domain. (And at the same time we can also register `mathematica.igraph.org` for IGraph/M?)

**Comment by szhorvat** [comment]
> Maybe we could settle on `r.igraph.org` as a subdomain and configure it as a custom subdomain for Github Pages, and do the same with Python so we could have `python.igraph.org` for the Read the Docs page?

Yes, that would be perfectly fine.

And yes, we should also migrate the Mma interface's website.

**Comment by iosonofabio** [comment]
subdomains are just fine, +1 from me. Whether it visibly redirects to an external domain (e.g. readthedocs) is not so important here I'd say. I understand ideally you'd wanna have canonical URLs etc. but even having decent links would be good for now.

**Comment by maelle** [comment]
I opened #743 as it seems to be the only element left to be solved.
