### ISSUE TITLE
Unable to compile or load igraph starting with 1.3.x on Windows 11, R4.2.2 w. IntelMKL

### ISSUE THREAD

**Issue by 3SMMZRjWgS** [igraph/rigraph#688]
This is a general case of Issue #537 and #534. Thanks to the troubleshooting done, I can understand what's causing the "quadmath_snprintf" error when compiling any igraph above 1.3.x on Windows 11 using R4.2.2 with the latest IntelMKL. Because in linking IntelMKL to R, default Rlapack.dll has to be replaced with a version from IntelMKL. That's why this problem also exists with the last MRO distribution 4.0.2.

For now, I've taken the downgrade approach by installing the last igraph 1.2.x version from archive. Is there a different work around for people who need IntelMKL matrix acceleration but also want to be able to use the latest igraph (1.4.x) on Windows 11?

**Comment by szhorvat** [comment]
Replacing DLLs is a dirty hack that is bound to break things eventually, unless the replacement provides exactly the same interface as the original (which is not the case here). The fact that the igraph 1.2.6 binaries work is accidental, and has to do with how they were compiled (with an old toolchain and an old R version) rather than any changes within the igraph source code.

In short, replacing DLLs this way will always be risky and inherently unreliable, and is not something that can be supported on our end.

The only way to make this work is to compile both R itself and igraph with the MKL (or with whichever BLAS/LAPACK you want to use). [MRO](https://mran.microsoft.com/) used to do this, but Microsoft no longer supports it, unfortunately. But you do have other options. Conda-Forge (Anaconda) provides both R and igraph. I am not sure which BLAS they link to, but they certainly have the infrastructure to start linking to OpenBLAS or the MKL if they are not already doing it. Or if you were willing to use other OS than Windows, many Linux distros and macOS package managers provide R linked to faster BLAS implementations.

**Comment by szhorvat** [comment]
To summarize, my suggestion is to look into Anaconda / Conda-Forge, see if it already includes a fast BLAS, and if not, request this from them.
