### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [igraph/rigraph#771]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by szhorvat** [comment]
If you are able to, please check the following:

 - Is this specific to the R interface of igraph, or is it in C/igraph? If in C/igraph, the report should go in the igraph (not rigraph) repo.
 - If it's in C/igraph, please check if the issue is present in the latest version. Note that R/igraph is currently based on version 0.9 of C/igraph, while the latest version is 0.10.

If this concerns file format readers, then it is very likely already fixed in 0.10. We are aware that it is easy to crash readers in 0.9, but that version will not receive updates in this area. Thus if you are planning to do further vulnerability testing, please focus your efforts on 0.10.

Regarding enabling secure reporting, someone else will respond in a couple of days, after Easter. In the meantime, please check the above of you can.

**Comment by szhorvat** [comment]
@igibek We discussed this internally, and decided not to enable private reporting at this point. 

Can you please file a normal (i.e. public) issue for the problem you found, so we can investigate?

**Comment by szhorvat** [comment]
@igibek Are you still planning to share the problem you found?
