### ISSUE TITLE
At core/core/vector.pmt:483 : Assertion failed: v->stor_begin != NULL

### ISSUE THREAD

**Issue by Amalthyia** [igraph/rigraph#833]
**Describe the bug**

This is the error I got and what it told me to do, so i'm trying to report the bug like it says.  I am trying to build my first igraph.  I gave it an edge_df with 2 columns.  There are 455 nodes, and 92664 weighted edges.  533849 total edges.   The first time I ran the code, I got a memory error.  I restarted computer and R studio.  Then ran the code again and got this error.  

```
igraph_net <- graph.edgelist(as.matrix(igraph_edge_df), directed = TRUE)
Error in (function (edges, n = max(edges), directed = TRUE)  : 
  At core/core/vector.pmt:483 : Assertion failed: v->stor_begin != NULL. This is an unexpected igraph error; please report this as a bug, along with the steps to reproduce it.
Please restart your R session to avoid crashes or other surprising behavior.
```

**To reproduce**
Complete steps or minimal example code to reproduce the problem.

Not sure what you need here.  
here is a sample of my df. 
```
> head(igraph_edge_df)
# A tibble: 6 × 2
        from         to
       <dbl>      <dbl>
1  527224666 1651997092
2 1651997092  997333574
3  997333574  616942789
4  616942789  238033486
5  238033486 1651997092
6 1651997092  648668531
```
and the code I used to create the graph 

```
# create an igraph object
igraph_net <- graph.edgelist(as.matrix(igraph_edge_df), directed = TRUE)
```

**Version information**

 - R/igraph version: ...
 igraph_1.4.3

 - R version: ...
R version 4.2.2 (2022-10-31 ucrt)

 - Operating system: ...
Windows 10 x64 (build 19044)

```
sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] igraph_1.4.3    lubridate_1.9.2 forcats_1.0.0   stringr_1.5.0   dplyr_1.1.2     purrr_1.0.1     readr_2.1.4    
 [8] tidyr_1.3.0     tibble_3.2.1    ggplot2_3.4.2   tidyverse_2.0.0

loaded via a namespace (and not attached):
 [1] rstudioapi_0.14  magrittr_2.0.3   hms_1.1.3        tidyselect_1.2.0 munsell_0.5.0    timechange_0.2.0
 [7] colorspace_2.1-0 R6_2.5.1         rlang_1.1.1      fansi_1.0.4      tools_4.2.2      grid_4.2.2      
[13] gtable_0.3.3     utf8_1.2.3       cli_3.6.1        withr_2.5.0      lifecycle_1.0.3  tzdb_0.4.0      
[19] vctrs_0.6.2      glue_1.6.2       stringi_1.7.12   compiler_4.2.2   pillar_1.9.0     generics_0.1.3  
[25] scales_1.2.1     pkgconfig_2.0.3 
```

**Comment by szhorvat** [comment]
@Amalthyia :

Thanks for reporting the issue. This happens because your edge list contains very large vertex IDs, such as `1651997092`. The largest number you have in your edgelist basically determines the number of vertices.  Here you are trying to create a graph with at least 1.6 billion vertices, which leads to an out-of-memory condition, which in turn is mishandled by igraph.

If the numbers in your edgelist are not meant to represent vertex IDs, convert the edgelist to strings using `as.character`. Then the entries will be interpreted as names.

Other notes: Please use `graph_from_edgelist()` instead of `graph.edgelist()`. The latter name is deprecated. If you evaluate `?graph.edgelist`, it actually takes you to `graph_from_edgelist`

----

@krlmlr @Antonov548 :

Regarding the mishandled out-of-memory condition: I suggest not spending time on debugging this right now. If the issue is in the C core, e.g. if the return value of a `calloc()` is not checked, it is almost certainly fixed in 0.10, which is extensively tested using [OSS-fuzz](https://google.github.io/oss-fuzz/) in a way that is likely to discover such problems.

It may also be in the R interface, but that's in flux right now, and OOM conditions are extremely difficult to reproduce.

**Comment by szhorvat** [comment]
> So both errors were due to the memory?

The root cause is that you were using `graph.edgelist()` incorrectly, which in turn caused igraph to try to reserve more memory than what was available. Think of it like this:

If the edge list contains integers, they are interpreted as vertex IDs. In other words, vertex `10` is the 10th vertex. You referred to the 1651997092th vertex, which implies that the graph has at least 1651997092 (1.65 billion) vertices. Was this your intention?

Example:

This creates a graph with 10 vertices because you referred to the 10th vertex:

```
> el <- matrix(c(9,10), ncol=2)
> g <- graph_from_edgelist(el)
> vcount(g)
[1] 10
```

If you want to create a graph with two vertices, one called "9", the other "10", convert the edge list entries to string. They will be interpreted as vertex names, not vertex IDs.

```
> el <- matrix(as.character(c(9,10)), ncol=2)
> g <- graph_from_edgelist(el)
> vcount(g)
[1] 2
> g
IGRAPH 1cc188a DN-- 2 1 -- 
+ attr: name (v/c)
+ edge from 1cc188a (vertex names):
[1] 9->10
> V(g)$name
[1] "9"  "10"
```


> I was following along with the datacamp class and they are using graph.edgelist().

`graph_from_edgelist` and `graph.edgelist` are different names for the very same function. `graph.edgelist` is deprected, and will be removed in the near future. To ensure that your code will work with future versions of igraph, do not use deprecated names. Switch to the new name, which you can find by looking up the function in the documentation. _Most_ functions with a `.` in the name are deprecated.

If possible, please inform datacamp that `graph.edgelist` is deprecated. `graph_from_edgelist` has been available since 2015 so there is no reason not to use it.

**Comment by Amalthyia** [comment]
Makes perfect sense now.  Thank you for the explanation. I changed everything to character.  That did indeed fix those issues.  
I'll let datacamp know if there is a way about the function. 
I appreciate the time you took in your explanation.
