### ISSUE TITLE
Option for max_cliques to output compressed text file

### ISSUE THREAD

**Issue by brooksambrose** [igraph/rigraph#863]
**What is the feature or improvement you would like to see?**

Add option to write file output of `max_cliques` to a file connection, or otherwise to a compressed file.

**Use cases for the feature**

I have a large (but not enormous) and very dense network of ~180,000 nodes. I ran the max_cliques output file and it hit 150GB before I stopped it, which is an untenably large file size for me.

**Comment by szhorvat** [comment]
I would say that realistically, this won't be implemented. It would be a lot of work, and it's even unclear how it could be done. C/igraph requires `FILE *` pointers. Currently, the R interface only takes file names as input, which is opens itself using `fopen`. According to a quick search, R does not have facilities to e.g. pass `stdout` to such a function, as the R API doesn't have any means to let R itself open the file and produce a `FILE *` pointers. (Correct me if I'm wrong @krlmlr)

Furthermore, this would be a of little use. The number of cliques increases exponentially with the graph size. A compression factor of 10 would only allow processing graphs that are just _a little bit_ larger.

Possible alternative solutions:

 - Use the Python or C interface of igraph, which can write to `stdout`. Pipe the output through `gzip`. 
 - The clique functions have callback versions in C. These could be exposed to R. Then cliques can be processed one-by-one instead of storing them all first. This should be a separate feature request.

**Comment by krlmlr** [comment]
Can you use `file = "/dev/stdout"` and then pipe? We have `stdout()` in R, and connections, but sending to `stdout` seems like a reasonable compromise.
