### ISSUE TITLE
deg seq bug

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/rigraph#88]
``` r
degree.sequence.game(c(1, 2, 7, 5, 7, 8, 3, 2, 2, 3), method = "vl")
#> Error in .Call("R_igraph_degree_sequence_game", as.numeric(out.deg), in.deg,  :
#> At gengraph_graph_molloy_optimized.cpp:380 : Error in graph_molloy_opt::havelhakimi(): Couldn't bind vertex 3 entirely (2 edges remaining), Internal error, likely a bug in igraph
```

**Comment by szhorvat** [comment]
This is not a graphical degree sequence, so expected. Closing.

**Comment by vtraag** [comment]
Shouldn't it provide a better warning though, as it now suggest it is a bug? Perhaps we could leave it open for that reason?

**Comment by szhorvat** [comment]
In Mathematica it looks like this:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/1212871/100522852-36e44e80-31ac-11eb-9b01-04d415846a96.png">

It issues two messages, and the second (an `EINVAL`) is more informative.

In R, we only see the first message (an `EINTERNAL`) because the R interface's error handler does not return (as the others do) but it immediately escapes by calling `error()`. I don't know why it does that, and whether it should be considered a "bug". The only possible issue I see with this is that when there are multiple errors, all but the first one are discarded. One might argue that when there is one error, there should not be more. On the other hand, in some cases having more than one may be the only easy way to convey enough information about what went wrong.

I'll leave dealing with the R part to others.

For the C core, I'll open an issue.
