### ISSUE TITLE
`R_igraph_community_label_propagation()` no longer returns `modularity`

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#881]
Fix as shown in a1f07562399b06039d994a75fa6aa7e852d90fb9 for the other affected functions.

**Comment by szhorvat** [comment]
This fix is not complete. I'll comment when I get home, on my phone

**Comment by szhorvat** [comment]
Basically, just make sure you pass weights to the modularity function.

**Comment by szhorvat** [comment]
@krlmlr The fix for `cluster_label_propagation` will indeed look similar to what you referenced, except that the `modularity()` call must also take the weights into account, if present.

However, the commit a1f07562399b06039d994a75fa6aa7e852d90fb9 is incorrect and should be reverted.

First, the modularity is already set by the C function. Use this when possible.

Second, notice that the C function returns not a single modularity value, but an entire vector, one number for each possible dendrogram cut.

Third, the weighted edge betweenness based community calculation is invalid, and we need to fix this on the C side. I would prefer not to add custom code for this specific function in high-level interfaces. See:

 - https://github.com/igraph/igraph/issues/1040
 - https://github.com/igraph/igraph/issues/2229 and

**Comment by szhorvat** [comment]
This was fixed by @Antonov548
